version: '2'
services:
  client:
    container_name: client
    build: ../..
    networks:
      - network_outer

  z0_p1:
    container_name: z0_p1
    build: ../..
    volumes:
      - ./p1/squid.conf:/etc/squid/squid.conf
      - ./p1/log:/var/log/squid
    networks:
      - network_outer
    ports:
      - 3128:3128

networks:
  network_outer:
