version: '2'
services:
  lab2_z1_proxy:
    container_name: lab2_z1_proxy
    build: .
    volumes:
      - ./proxy/squid.conf:/etc/squid/squid.conf
      - ./proxy/log:/var/log/squid
      - ./proxy/acl/:/etc/squid/acl/
    networks:
      - network_outer
    ports:
      - 3128:3128

networks:
  network_outer:
