version: '3.5'
services:
  client:
    container_name: client
    build: ../.
    networks:
      - network_outer

  p1:
    container_name: z3_p1
    build: ../.
    volumes:
      - ./p1/squid.conf:/etc/squid/squid.conf
      - ./p1/log:/var/log/squid
    networks:
      - network_outer

  p2:
    container_name: z3_p2
    build: ../.
    volumes:
      - ./p2/squid.conf:/etc/squid/squid.conf
      - ./p2/log:/var/log/squid
    networks:
      - network_outer

  p3:
    container_name: z3_p3
    build: ../.
    volumes:
      - ./p3/squid.conf:/etc/squid/squid.conf
      - ./p3/log:/var/log/squid
    networks:
      - network_outer

networks:
  network_outer:
