version: '3.5'
services:
  client:
    container_name: client
    build: ../.
    networks:
      - network_outer

  p1:
    container_name: z4_p1
    build: ../.
    volumes:
      - ./p1/squid.conf:/etc/squid/squid.conf
      - ./p1/log:/var/log/squid
    networks:
      - network_inner2

  p2:
    container_name: z4_p2
    build: ../.
    volumes:
      - ./p2/squid.conf:/etc/squid/squid.conf
      - ./p2/log:/var/log/squid
    networks:
      - network_inner
      - network_inner2

  p3:
    container_name: z4_p3
    build: ../.
    volumes:
      - ./p3/squid.conf:/etc/squid/squid.conf
      - ./p3/log:/var/log/squid
    networks:
      - network_outer
      - network_inner

networks:
  network_outer:
  network_inner:
  network_inner2:
